version = 1

[[analyzers]]
name = "javascript"
enabled= true

  [analyzers.meta]
  plugins = ["angular"]

[[analyzers]]
name = "test-coverage"
enabled= true

[[transformers]]
name = "prettier"
enabled = true
